suppress:
  paths:
    - "package-lock.json"
    - "**/package-lock.json"
    - "yarn.lock"
    - "**/yarn.lock"
    - "pnpm-lock.yaml"
    - "**/pnpm-lock.yaml"
    - "Cargo.lock"
    - "**/Cargo.lock"
