import hashlib
import re
import numpy as np

# Test file patterns — skip classification to avoid noisy false positives in test suites
_TEST_FILE_RE = re.compile(r"(^|/)test[_-]|[_-]test\.py$|/tests?/", re.I)

# Indicators organised by category — all matched case-insensitively against individual lines.
# Format: (pattern_string, severity, category_label)
_INDICATORS: list[tuple[str, str, str]] = [
    # ── Placeholder / skeleton markers ──────────────────────────────────────
    ("todo.*verif.*production",         "MEDIUM", "Unverified placeholder"),
    ("todo.*replace.*before.*prod",     "MEDIUM", "Unverified placeholder"),
    ("todo.*remove.*before.*commit",    "MEDIUM", "Unverified placeholder"),
    ("fixme.*security",                 "MEDIUM", "Unverified placeholder"),
    ("placeholder.*auth",               "MEDIUM", "Unverified placeholder"),
    ("placeholder.*key",                "MEDIUM", "Unverified placeholder"),
    ("placeholder.*token",              "MEDIUM", "Unverified placeholder"),
    ("placeholder.*secret",             "MEDIUM", "Unverified placeholder"),
    ("insert.*logic.*here",             "MEDIUM", "Unverified placeholder"),
    ("add.*implementation.*here",       "MEDIUM", "Unverified placeholder"),
    ("not.*implemented.*yet",           "MEDIUM", "Unverified placeholder"),
    ("implement.*this.*later",          "MEDIUM", "Unverified placeholder"),
    ("temporary.*workaround",           "MEDIUM", "Unverified placeholder"),
    ("temp.*fix.*remove",               "MEDIUM", "Unverified placeholder"),

    # ── Auth / credential stubs ──────────────────────────────────────────────
    ("fake.*password",                  "HIGH",   "Credential stub"),
    ("dummy.*password",                 "HIGH",   "Credential stub"),
    ("test.*password",                  "HIGH",   "Credential stub"),
    ("hardcoded.*password",             "HIGH",   "Credential stub"),
    ("password.*=.*['\"]password['\"]", "HIGH",   "Credential stub"),
    ("password.*=.*['\"]123",          "HIGH",   "Credential stub"),
    ("secret.*=.*['\"]secret['\"]",    "HIGH",   "Credential stub"),
    ("token.*=.*['\"]token['\"]",      "HIGH",   "Credential stub"),
    ("api_key.*=.*['\"]test",          "HIGH",   "Credential stub"),
    ("api_key.*=.*['\"]fake",          "HIGH",   "Credential stub"),
    ("auth.*bypass",                    "HIGH",   "Credential stub"),
    ("skip.*authentication",            "HIGH",   "Credential stub"),
    ("disable.*auth",                   "HIGH",   "Credential stub"),

    # ── Mock / fake imports ──────────────────────────────────────────────────
    ("from internal_ai_test import",    "MEDIUM", "Hallucinated import"),
    ("import artificial_intelligence",  "MEDIUM", "Hallucinated import"),
    ("import mock_",                    "MEDIUM", "Hallucinated import"),
    ("import fake_",                    "MEDIUM", "Hallucinated import"),
    ("from mock_",                      "MEDIUM", "Hallucinated import"),
    ("from fake_",                      "MEDIUM", "Hallucinated import"),
    ("import stub_",                    "MEDIUM", "Hallucinated import"),
    ("from stub_",                      "MEDIUM", "Hallucinated import"),

    # ── AI generation artifacts ──────────────────────────────────────────────
    ("insert mock api implementation",  "MEDIUM", "AI artifact"),
    ("as an ai language model",         "MEDIUM", "AI artifact"),
    ("as a language model",             "MEDIUM", "AI artifact"),
    ("this is sample code",             "MEDIUM", "AI artifact"),
    ("this is example code",            "MEDIUM", "AI artifact"),
    ("generated by (gpt|claude|llm|copilot|gemini)",  "MEDIUM", "AI artifact"),
    ("auto.?generated.*do not edit",    "LOW",    "AI artifact"),
    ("note:.*verify.*in production",    "MEDIUM", "AI artifact"),
    ("ensure.*replace.*with.*actual",   "MEDIUM", "AI artifact"),
    ("replace.*this.*with.*your",       "MEDIUM", "AI artifact"),
    ("add your.*here",                  "MEDIUM", "AI artifact"),
    ("your api key here",               "MEDIUM", "AI artifact"),
    ("your secret here",                "MEDIUM", "AI artifact"),

    # ── Dead code / incomplete stubs ─────────────────────────────────────────
    ("raise notimplementederror",       "LOW",    "Incomplete stub"),
    ("pass  *#.*todo",                  "LOW",    "Incomplete stub"),
    (r"\.\.\.$",                        "LOW",    "Incomplete stub"),  # bare ellipsis body
    ("return none  *#.*todo",           "LOW",    "Incomplete stub"),
    ("return \\[\\]  *#.*todo",         "LOW",    "Incomplete stub"),
]

# Pre-compile all patterns for speed
_COMPILED: list[tuple[re.Pattern, str, str, str]] = [
    (re.compile(pattern, re.I), pattern, severity, label)
    for pattern, severity, label in _INDICATORS
]


class LocalSequenceClassifier:
    def process_inference_eval(self, code_data: str, filename: str = "") -> list:
        # Skip test files — stubs and placeholders are legitimate there
        if _TEST_FILE_RE.search(filename):
            return []

        anomalies = []
        lines = code_data.splitlines()

        for index, text_line in enumerate(lines, 1):
            for compiled, raw_pattern, severity, label in _COMPILED:
                if compiled.search(text_line):
                    anomalies.append({
                        "line_number": index,
                        "anomaly_type": "AI Structural Hallucination",
                        "severity": severity,
                        "description": (
                            f"{label} detected: pattern '{raw_pattern}' matched. "
                            f"Verify this is intentional production code."
                        ),
                        "code_snippet": text_line.strip(),
                    })
                    break  # one finding per line — don't double-report

        return anomalies

    def generate_embedding_vector(self, text_payload: str) -> list:
        seed = int(hashlib.md5(text_payload.encode()).hexdigest(), 16) % (2**32)
        rng = np.random.RandomState(seed)
        vec = rng.randn(1536)
        return (vec / np.linalg.norm(vec)).tolist()


sequence_classifier_node = LocalSequenceClassifier()
